# Generated by Django 4.1.7 on 2023-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=150, null=True)),
                ("phone", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "admin"), ("user", "user")],
                        default="user",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="user_avatars/")),
                ("is_active", models.BooleanField(default=True, null=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["email"],
            },
        ),
    ]
